import Footer from './(components)/footer/Footer'
import Header from './(components)/header/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Doctor Appointment',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <>
    
    <html lang="en">

      <body className={inter.className}>{children}</body>
  <Footer />
    </html>
    
    </>
  )
}
